### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by stefkpl** [khoih-prog/EthernetWebServer_STM32#2]
Hello,
I use this hardware : Nucleo-32 F303K8 with 64Kof Flash and ENC28J60 shield.
If I try to compile with `#define USE_UIP_ETHERNET false;` directive. It compiling fine.

I try to compile AdvancedWebServer exemple but I have theses errors :

> In file included from D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/EthernetWebServer_STM32.h:208,
>                  from C:\Users\Stef\AppData\Local\Temp\arduino_modified_sketch_13315\AdvancedWebServer.ino:100:
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/EthernetWebServer_STM32-impl.h: In member function 'void EthernetWebServer::handleClient()':
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/EthernetWebServer_STM32-impl.h:175:20: error: 'class UIPClient' has no member named 'setTimeout'
>   175 |     _currentClient.setTimeout(HTTP_MAX_SEND_WAIT);
>       |                    ^~~~~~~~~~
> In file included from D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/EthernetWebServer_STM32.h:209,
>                  from C:\Users\Stef\AppData\Local\Temp\arduino_modified_sketch_13315\AdvancedWebServer.ino:100:
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h: In function 'char* readBytesWithTimeout(UIPClient&, size_t, size_t&, int)':
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:54:12: error: 'class UIPClient' has no member named 'readBytes'
>    54 |     client.readBytes(buf + dataLength, newLength);
>       |            ^~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h: In member function 'bool EthernetWebServer::_parseRequest(UIPClient&)':
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:63:23: error: 'class UIPClient' has no member named 'readStringUntil'
>    63 |   String req = client.readStringUntil('\r');
>       |                       ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:64:10: error: 'class UIPClient' has no member named 'readStringUntil'
>    64 |   client.readStringUntil('\n');
>       |          ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:149:20: error: 'class UIPClient' has no member named 'readStringUntil'
>   149 |       req = client.readStringUntil('\r');
>       |                    ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:150:14: error: 'class UIPClient' has no member named 'readStringUntil'
>   150 |       client.readStringUntil('\n');
>       |              ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:226:20: error: 'class UIPClient' has no member named 'readStringUntil'
>   226 |       req = client.readStringUntil('\r');
>       |                    ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:227:14: error: 'class UIPClient' has no member named 'readStringUntil'
>   227 |       client.readStringUntil('\n');
>       |              ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h: In member function 'bool EthernetWebServer::_parseForm(UIPClient&, String, uint32_t)':
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:355:19: error: 'class UIPClient' has no member named 'readStringUntil'
>   355 |     line = client.readStringUntil('\r');
>       |                   ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:359:10: error: 'class UIPClient' has no member named 'readStringUntil'
>   359 |   client.readStringUntil('\n');
>       |          ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:371:21: error: 'class UIPClient' has no member named 'readStringUntil'
>   371 |       line = client.readStringUntil('\r');
>       |                     ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:372:14: error: 'class UIPClient' has no member named 'readStringUntil'
>   372 |       client.readStringUntil('\n');
>       |              ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:394:25: error: 'class UIPClient' has no member named 'readStringUntil'
>   394 |           line = client.readStringUntil('\r');
>       |                         ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:395:18: error: 'class UIPClient' has no member named 'readStringUntil'
>   395 |           client.readStringUntil('\n');
>       |                  ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:399:20: error: 'class UIPClient' has no member named 'readStringUntil'
>   399 |             client.readStringUntil('\r');
>       |                    ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:400:20: error: 'class UIPClient' has no member named 'readStringUntil'
>   400 |             client.readStringUntil('\n');
>       |                    ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:407:29: error: 'class UIPClient' has no member named 'readStringUntil'
>   407 |               line = client.readStringUntil('\r');
>       |                             ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:408:22: error: 'class UIPClient' has no member named 'readStringUntil'
>   408 |               client.readStringUntil('\n');
>       |                      ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:471:22: error: 'class UIPClient' has no member named 'readBytes'
>   471 |               client.readBytes(endBuf, boundary.length());
>       |                      ^~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:485:31: error: 'class UIPClient' has no member named 'readStringUntil'
>   485 |                 line = client.readStringUntil(0x0D);
>       |                               ^~~~~~~~~~~~~~~
> D:\Users\Stef\Documents\Arduino\libraries\EthernetWebServer_STM32\src/Parsing_STM32-impl.h:486:24: error: 'class UIPClient' has no member named 'readStringUntil'
>   486 |                 client.readStringUntil(0x0A);
>       |                        ^~~~~~~~~~~~~~~

Have you got any idea ?

Best regards

**Comment by khoih-prog** [comment]
The Nucleo-32 F303K8 with ENC28J60 shield is not supported as it has **no HardwareSPI** necessary for UIPEthernet

![Selection_445](https://user-images.githubusercontent.com/57012152/85870901-abe5cf00-b79b-11ea-8945-395fca0d7f14.png)

Compiling for other Nucleo-32 boards (L412KB, L432KC, G431KB) with ENC28J60 is OK.

![Selection_444](https://user-images.githubusercontent.com/57012152/85870921-b2744680-b79b-11ea-9a88-80684bf8dbf9.png)

You have to use another supported board.

**Comment by stefkpl** [comment]
I can compile whitout SPI error with this patch [new STM32 core F3/F4 compatibility ](https://github.com/UIPEthernet/UIPEthernet/commit/c6d6519a260166b722b9cee5dd1f0fb2682e6782).
But I have class error.

**Comment by khoih-prog** [comment]
I can compile Nucleo-32 F303K8 without error using the patch now.

![Selection_446](https://user-images.githubusercontent.com/57012152/85881043-fde22100-b7aa-11ea-9f41-9ed92571bae5.png)

You have to check your libraries' installation to see what's missing. Re-install the UIPEthernet lib.

**Comment by stefkpl** [comment]
I re-install 3 times UIPEthernet lib, I think I must remove all librairies on my computer and double check dependencies.
Thank's :)

**Comment by khoih-prog** [comment]
@stefkpl 

The function setTimeout() was defined in files

~/.arduino15/packages/STM32/hardware/stm32/1.9.0/cores/arduino/Stream.h/cpp as follows

`void setTimeout(unsigned long timeout);  // sets maximum milliseconds to wait for stream data, default is 1 second`

I think you have to (re)install the latest STM32 core v1.9.0 using Arduino IDE Tools->Boards Manager

![Selection_449](https://user-images.githubusercontent.com/57012152/85887395-b90fb780-b7b5-11ea-8fad-558f5b6ca8d1.png)

**Comment by stefkpl** [comment]
@khoih-prog 
I have re-install (on 2 computers) from *scratch* arduino IDE, re-install only UIPEthernet and EthernetWebServer_STM32 libs and STM32 Boards.
So, EthernetWebServer_STM32 lib try to accessing stream class, but UIP lib don't have stream class ....
Not only **.setTimeout** but **.readBytes** and **.readStringUntil**.

Why can you compile and not me ? I don't understand!  
Have you got overload or other dependencies on your computer?
![image](https://user-images.githubusercontent.com/25172355/85991203-658aad00-b9f3-11ea-9b55-17de5936002e.png)

Thank you

**Comment by khoih-prog** [comment]
@stefkpl 

> So, EthernetWebServer_STM32 lib try to accessing stream class, but UIP lib don't have stream class

This is the way C++ works:

**The Class UIPClient <= Class Client of STM32 cores <= Class Stream  of STM32 cores**

In file UIPClient.h

```
class UIPClient : public Client
```
In file ~/.arduino15/packages/STM32/hardware/stm32/1.9.0/cores/arduino/Client.h

```
class Client : public Stream
```

In file ~/.arduino15/packages/STM32/hardware/stm32/1.9.0/cores/arduino/Stream.h

```
class Stream : public Print
{
...
    void setTimeout(unsigned long timeout);  // sets maximum milliseconds to wait for stream data, default is 1 second
...
    virtual size_t readBytes(char *buffer, size_t length);  // read chars from stream into buffer
    size_t readBytes(uint8_t *buffer, size_t length)
    {
      return readBytes((char *)buffer, length);
    }
    // terminates if length characters have been read or timeout (see setTimeout)
    // returns the number of characters placed in the buffer (0 means no valid data found)

    virtual size_t readBytesUntil(char terminator, char *buffer, size_t length);  // as readBytes with terminator character
    size_t readBytesUntil(char terminator, uint8_t *buffer, size_t length)
    {
      return readBytesUntil(terminator, (char *)buffer, length);
    }
    // terminates if length characters have been read, timeout, or if the terminator character  detected
    // returns the number of characters placed in the buffer (0 means no valid data found)

    // Arduino String functions to be added here
    String readString();
    String readStringUntil(char terminator);
```

> I think you have to (re)install the latest **STM32 core v1.9.0** using Arduino IDE Tools->Boards Manager

If you've already done the (re)installation, please check if you have these files in STM32 cores v1.9.0 folder /.arduino15/packages/STM32/hardware/stm32/1.9.0/cores/arduino/

1. Client.h
2. Stream.h/cpp

If you don't see those files, there is some kind of bugs in Arduino IDE when installing **STM32 core v1.9.0 for Windows.**

I'm afraid you're on your own now and I can't help any further.

**Comment by stefkpl** [comment]
I found them, but Arduino use mbed libs and I don't know why. 
Perhaps because directives are forced by **STM32F3** define.
When I force manualy arduino libs (by remove *mebed/* and move mbed directory from UIPEthernet directory) and not mbed, I have other errors :(

**Comment by stefkpl** [comment]
After many try, I solved the problem. It's not your lib. 
The UIPEthernet don't work with STM32F3 board because configuration mix, in this case, mbed and Arduino libs.
Thank you for you help.
