### ISSUE TITLE
Sending raw ethernet frame with the lan8742a?

### ISSUE THREAD

**Issue by particlerain** [khoih-prog/EthernetWebServer_STM32#5]
Is there a possibility to send raw ethernet frame (IP_RAW) with the lan8742a?
I see that this is possible with the w5xxx already, but would like to do it through the builtin phy on f767.

**Comment by khoih-prog** [comment]
I believe it's totally possible, but it must be the feature provided by the [**STM32Ethernet** library](https://github.com/stm32duino/STM32Ethernet) on which this [EthernetWebServer_STM32](https://github.com/khoih-prog/**EthernetWebServer_STM32**) relies.

I suggest you open an enhancement request in [STM32Ethernet issues](https://github.com/stm32duino/STM32Ethernet/issues).

I'm closing the issue now.

Regards,
