### ISSUE TITLE
LAN8720

### ISSUE THREAD

**Issue by Ddh012345dhD** [khoih-prog/EthernetWebServer_STM32#6]
Thư viện này có giao tiếp được với LAN8720 không ạ.

**Comment by khoih-prog** [comment]
Thanks for your interests in the library.

Currently, **LAN8720 is not supported** and I currently have no plan to add the support to it.

But if there are **more requests**, I certainly will spend some time on the enhancement.

Try to use the more popular **W5x00** (better) or **ENC28J60** (with [**EthernetENC**](https://github.com/jandrassy/EthernetENC) library)

**Comment by khoih-prog** [comment]
I just added the LAN8720 support to **STM32F4** and **STM32F7** for you to test, using this [**EthernetWebServer_STM32** library](https://github.com/khoih-prog/EthernetWebServer_STM32), at [**STM32_LAN8720**](https://github.com/khoih-prog/EthernetWebServer_STM32/tree/master/examples/STM32_LAN8720).

The test examples are

1. [AdvancedWebServer_LAN8720](https://github.com/khoih-prog/EthernetWebServer_STM32/tree/master/examples/STM32_LAN8720/AdvancedWebServer_LAN8720)
2.  [UdpNTPClient_LAN8720](https://github.com/khoih-prog/EthernetWebServer_STM32/tree/master/examples/STM32_LAN8720/UdpNTPClient_LAN8720)
3.  [UdpSendReceive_LAN8720](https://github.com/khoih-prog/EthernetWebServer_STM32/tree/master/examples/STM32_LAN8720/UdpSendReceive_LAN8720)
4.  [WebClientRepeating_LAN8720](https://github.com/khoih-prog/EthernetWebServer_STM32/tree/master/examples/STM32_LAN8720/WebClientRepeating_LAN8720)
5.  [WebClient_LAN8720](https://github.com/khoih-prog/EthernetWebServer_STM32/tree/master/examples/STM32_LAN8720/WebClient_LAN8720)
6.  [WebServer_LAN8720](https://github.com/khoih-prog/EthernetWebServer_STM32/tree/master/examples/STM32_LAN8720/WebServer_LAN8720)

---

# Wiring

|LAN8720 PHY|---|STM32F4|
|:-:|:-:|:-:|
|TX1|<--->|PB_13|
|TX_EN|<--->|PB_11|
|TX0|<--->|PB_12|
|RX0|<--->|PC_4|
|RX1|<--->|PC_5|
|nINT/RETCLK|<--->|PA_1|
|CRS|<--->|PA_7|
|MDIO|<--->|PA_2|
|MDC|<--->|PC_1|
|GND|<--->|GND|
|VCC|<--->|+3.3V|


If tested OK, I'll include them as well as more examples into the new release.

**Comment by Ddh012345dhD** [comment]
![image](https://user-images.githubusercontent.com/54657357/114256807-2b205880-99e6-11eb-930e-45155badb456.png)
i tested but IDE warning No such file or directory  functional-vlpp.h

**Comment by khoih-prog** [comment]
You have to read [Prerequisites](https://github.com/khoih-prog/EthernetWebServer_STM32#prerequisites) then install all the dependent libraries

---


## Prerequisites

 1. [`Arduino IDE 1.8.13+` for Arduino](https://www.arduino.cc/en/Main/Software)
 2. [`Arduino Core for STM32 v1.9.0+`](https://github.com/stm32duino/Arduino_Core_STM32) for STM32 boards. [![GitHub release](https://img.shields.io/github/release/stm32duino/Arduino_Core_STM32.svg)](https://github.com/stm32duino/Arduino_Core_STM32/releases/latest)
 3. [**Functional-VLPP library v1.0.2+**](https://github.com/khoih-prog/functional-vlpp) to use server's lambda function. To install. check [![arduino-library-badge](https://www.ardu-badge.com/badge/Functional-Vlpp.svg?)](https://www.ardu-badge.com/Functional-Vlpp)
 4. For built-in LAN8742A Ethernet:
   - [`STM32Ethernet library v1.2.0+`](https://github.com/stm32duino/STM32Ethernet) for built-in LAN8742A Ethernet on (Nucleo-144, Discovery). [![GitHub release](https://img.shields.io/github/release/stm32duino/STM32Ethernet.svg)](https://github.com/stm32duino/STM32Ethernet/releases/latest)
   - [`LwIP library v2.1.2+`](https://github.com/stm32duino/LwIP) for built-in LAN8742A Ethernet on (Nucleo-144, Discovery). [![GitHub release](https://img.shields.io/github/release/stm32duino/LwIP.svg)](https://github.com/stm32duino/LwIP/releases/latest)
 5. For W5x00 Ethernet:
   - [`Ethernet library v2.0.0+`](https://github.com/arduino-libraries/Ethernet) for W5100, W5200 and W5500.  [![GitHub release](https://img.shields.io/github/release/arduino-libraries/Ethernet.svg)](https://github.com/arduino-libraries/Ethernet/releases/latest)
   - [`EthernetLarge library v2.0.0+`](https://github.com/OPEnSLab-OSU/EthernetLarge) for W5100, W5200 and W5500.
   - [`Ethernet2 library v1.0.4+`](https://github.com/khoih-prog/Ethernet2) for W5500. [![GitHub release](https://img.shields.io/github/release/adafruit/Ethernet2.svg)](https://github.com/adafruit/Ethernet2/releases/latest)
   - [`Ethernet3 library v1.5.5+`](https://github.com/sstaub/Ethernet3) for W5500/WIZ550io/WIZ850io/USR-ES1 with Wiznet W5500 chip. [![GitHub release](https://img.shields.io/github/release/sstaub/Ethernet3.svg)](https://github.com/sstaub/Ethernet3/releases/latest)
 6. For ENC28J60 Ethernet:
   - [`EthernetENC library v2.0.0+`](https://github.com/jandrassy/EthernetENC) for ENC28J60. [![GitHub release](https://img.shields.io/github/release/jandrassy/EthernetENC.svg)](https://github.com/jandrassy/EthernetENC/releases/latest). **New and Better**
   - [`UIPEthernet library v2.0.9+`](https://github.com/UIPEthernet/UIPEthernet) for ENC28J60. [![GitHub release](https://img.shields.io/github/release/UIPEthernet/UIPEthernet.svg)](https://github.com/UIPEthernet/UIPEthernet/releases/latest)

**Comment by khoih-prog** [comment]
Compile OK for Generic ST32F4 (F407VE, VG, ZE, etc.)

![Selection_705](https://user-images.githubusercontent.com/57012152/114257068-65104100-998b-11eb-8740-7f374b5a1902.png)

**Comment by khoih-prog** [comment]
The new release [**EthernetWebServer_STM32** v1.2.0](https://github.com/khoih-prog/EthernetWebServer_STM32/releases/tag/v1.2.0) has been published to add support to **LAN8720** for many **STM32F4** and **SM32F7** boards.

Have a look at [**HOWTO use STM32F4 with LAN8720**](https://github.com/khoih-prog/EthernetWebServer_STM32#howto-use-stm32f4-with-lan8720) if you have problem.

It's working reliably and you can see at

[**AdvancedWebServer_LAN8720 on BLACK_F407VE, using LAN8720 Ethernet and STM32Ethernet Library**](https://github.com/khoih-prog/EthernetWebServer_STM32#12-advancedwebserver_lan8720-on-black_f407ve-using-lan8720-ethernet-and-stm32ethernet-library)

![AdvancedWebServer_LAN8720](https://user-images.githubusercontent.com/57012152/114298718-bbfa4100-9a85-11eb-995b-e83c7efbf863.png)


---

### Releases v1.2.0

1. Add support to **LAN8720** Ethernet for many **STM32F4** (F407xx, NUCLEO_F429ZI) and **STM32F7** (DISCO_F746NG, NUCLEO_F746ZG, NUCLEO_F756ZG) boards.
2. Add LAN8720 examples
3. Add Packages' Patches for STM32 to use LAN8720 with STM32Ethernet and LwIP libraries

**Comment by khoih-prog** [comment]
Just a note that this solved issue was inadequately mentioned in [**Support communication LAN8720** #1346](https://github.com/stm32duino/Arduino_Core_STM32/issues/1346)
